package main

import (
    "fmt"
    "net/http"
    //"github.com/Sirupsen/logrus"
    //"github.com/sebest/logrusly"
    "encoding/json"
    "io/ioutil"

)

type AutoGenerated struct {
	Data struct {
		Type string `json:"type"`
		Attributes struct {
			GameModeStats struct {
				SoloFpp struct {
					Assists             int     `json:"assists"`
					BestRankPoint       float64 `json:"bestRankPoint"`
					Boosts              int     `json:"boosts"`
					DBNOs               int     `json:"dBNOs"`
					DailyKills          int     `json:"dailyKills"`
					DailyWins           int     `json:"dailyWins"`
					DamageDealt         float64 `json:"damageDealt"`
					Days                int     `json:"days"`
					HeadshotKills       int     `json:"headshotKills"`
					Heals               int     `json:"heals"`
					KillPoints          int     `json:"killPoints"`
					Kills               int     `json:"kills"`
					LongestKill         float64 `json:"longestKill"`
					LongestTimeSurvived float64 `json:"longestTimeSurvived"`
					Losses              int     `json:"losses"`
					MaxKillStreaks      int     `json:"maxKillStreaks"`
					MostSurvivalTime    float64 `json:"mostSurvivalTime"`
					RankPoints          int     `json:"rankPoints"`
					RankPointsTitle     string  `json:"rankPointsTitle"`
					Revives             int     `json:"revives"`
					RideDistance        float64 `json:"rideDistance"`
					RoadKills           int     `json:"roadKills"`
					RoundMostKills      int     `json:"roundMostKills"`
					RoundsPlayed        int     `json:"roundsPlayed"`
					Suicides            int     `json:"suicides"`
					SwimDistance        int     `json:"swimDistance"`
					TeamKills           int     `json:"teamKills"`
					TimeSurvived        float64 `json:"timeSurvived"`
					Top10S              int     `json:"top10s"`
					VehicleDestroys     int     `json:"vehicleDestroys"`
					WalkDistance        float64 `json:"walkDistance"`
					WeaponsAcquired     int     `json:"weaponsAcquired"`
					WeeklyKills         int     `json:"weeklyKills"`
					WeeklyWins          int     `json:"weeklyWins"`
					WinPoints           int     `json:"winPoints"`
					Wins                int     `json:"wins"`
				} `json:"solo-fpp"`
            }
        }
    }
}

func main() {
    file, err := http.Get("https://api.pubg.com/shards/steam/players/account.ab3ebdd2cbe44e5996bad678dd15ac3b/seasons/lifetime")
    if err != nil {
        fmt.Println("Error")
    }

    fmt.Println("Successfully Opened")
    defer file.Body.Close()

    byteValue, _ := ioutil.ReadAll(file.Body)

    var stats AutoGenerated

    json.Unmarshal(byteValue, &stats)

    fmt.Println(stats)

}
